In [1]:
import numpy as np
import matplotlib.pylab as plt

raw_data_X =[[3.3,2.3],
             [3.1,1.7],
             [1.3,3.3],
             [3.5,4.6],
             [2.2,2.8],
             [7.4,4.6],
             [5.7,3.5],
             [9.1,2.5],
             [7.7,3.4],
             [7.9,0.7]
            ]
raw_data_y = [0,0,0,0,0,1,1,1,1,1]

X_train = np.array(raw_data_X)
y_train = np.array(raw_data_y)

x =np.array([8.0,3.3])

In [15]:
%run pycharm-project/KNNfunction/KNN.py

In [16]:
KNN_classify(6,X_train,y_train,x)

1

### scikit-learn中的knn算法

In [19]:
from sklearn.neighbors import KNeighborsClassifier

In [20]:
kNN_classifier = KNeighborsClassifier(n_neighbors=6)

In [21]:
kNN_classifier.fit(X_train,y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=6, p=2,
           weights='uniform')

In [24]:
X_predict = x.reshape(1,-1)

In [25]:
X_predict

array([[8. , 3.3]])

In [26]:
kNN_classifier.predict(X_predict)

array([1])

In [27]:
%run pycharm-project/KNNfunction/kNN1.py

In [28]:
knn_clf = KNNClassifier(k=6)

In [30]:
knn_clf.fit(X_train,y_train)

In [31]:
%run pycharm-project/KNNfunction/kNN1.py

In [32]:
knn_clf = KNNClassifier(k=6)

In [33]:
knn_clf.fit(X_train,y_train)

KNN(k=6)

In [34]:
y_predict = knn_clf.predict(X_predict)

In [35]:
y_predict

array([1])