In [2]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn import datasets

In [3]:
iris = datasets.load_iris()

In [15]:
X = iris.data
y = iris.target

In [16]:
X.shape()

TypeError: 'tuple' object is not callable

In [17]:
X.shape

(150, 4)

In [7]:
y.shape

(150,)

###train_test_slipt

In [8]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [21]:
shuffle_indexes = np.random.permutation(len(X)) #乱序处理,对x进行索引顺序的乱序排列

In [22]:
shuffle_indexes

array([117, 145, 104,  13,  65,  15,  35,   9,  42,  22,  24,  96, 140,
        95,   6,  44, 114,  55,  78, 147,  60, 122, 146,  74, 131,  68,
        16,  84,  45,  70, 100,  89, 137,  50, 118, 101,  97,  47, 108,
        26, 107,  53, 109, 132,  94,  36, 143,  40,  41,  32,  31,  61,
        38,  63,  67,   3,  30,  99, 124,   1, 112,  43, 134,  37,  82,
        56,  77,  91,  10, 115,  81,  79, 130, 141,  48,  25,  71,  29,
        64, 105,  88, 128, 136,  85,  14,  66, 119, 121,  39,  90, 127,
       106,   7,  23,  72,  80,  76,  34, 148, 123,  62, 142, 144,  20,
        12,  49, 116,  58, 126,  54,  46, 113,  93,  57,  73, 125,  98,
        69,  33,  19,  27,  52, 139, 111,  28,  17,  11,   8,   4,  51,
        86, 138, 133,   0, 102,   2, 103,  92,  75,  83,  87,  21, 149,
        59,  18, 110, 135, 120,   5, 129])

In [11]:
test_ratio = 0.2   #选取多少个元素作为测试数据集的比例
test_size = int(len(x)*test_ratio)

In [12]:
test_size

30

In [14]:
test_indexes = shuffle_indexes[:test_size]  #前20%是测试数据集，后80%是训练数据集
train_indexes = shuffle_indexes[test_size:]

In [24]:
X_train = X[train_indexes]
y_train = y[train_indexes]

X_test = X[test_indexes]
y_test = y[test_indexes]

In [27]:
print(X_train.shape)
print(y_train.shape)

(120, 4)
(120,)


In [28]:
print(X_test.shape)
print(y_test.shape)

(30, 4)
(30,)


In [29]:
from playML.kNN import KNNClassifier

ModuleNotFoundError: No module named 'playML'

In [30]:
%run pycharm-project/KNNfunction/kNN1.py

In [31]:
my_knn_clf = KNNClassifier(k=3)

In [32]:
my_knn_clf.fit(X_train,y_train)

KNN(k=3)

In [33]:
y_predict = my_knn_clf.predict(X_test)

In [34]:
y_predict

array([0, 1, 0, 1, 0, 0, 1, 1, 2, 2, 1, 0, 0, 1, 2, 0, 2, 0, 1, 1, 2, 1,
       1, 1, 1, 0, 1, 1, 1, 2])

In [35]:
y_test

array([0, 1, 0, 1, 0, 0, 1, 1, 2, 2, 1, 0, 0, 1, 2, 0, 2, 0, 1, 1, 2, 1,
       1, 2, 1, 0, 1, 1, 1, 2])

In [36]:
sum(y_predict == y_test)

29

In [37]:
sum(y_predict == y_test)/len(y_test)

0.9666666666666667

###sklearin中的train_test_slipt

In [38]:
from sklearn.model_selection import train_test_split

In [39]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2)