In [1]:
import numpy as np  
import matplotlib.pyplot as plt 

In [2]:
m = 100000

x = np.random.normal(size = m)
X = x.reshape(-1,1)
y = 4. * x + 3. + np.random.normal(0, 3, size= m)

In [3]:
def J(theta , X_b , y):
    try :
        return np.sum((y - X_b.dot(theta)) **2 )/len(y)
    except:
        return float('inf')
def dJ(theta,X_b,y):
    return X_b.T.dot(X_b.dot(theta)- y)*2./len(y)
def gradient_descent(X_b,y,initial_theta,eta,n_iters = 1e4,epsilon = 1e-8):
    theta = initial_theta
    cur_iter = 0
    while cur_iter < n_iters:
        gradient = dJ(theta,X_b,y)
        last_theta = theta
        theta = theta - eta *gradient
        if(abs(J(theta,X_b,y) - J(last_theta,X_b,y))<epsilon):
            break
        cur_iter += 1
    return theta


In [22]:
%%time 
X_b = np.hstack([np.ones((len(X),1)),X])
initial_theta = np.zeros(X_b.shape[1])
eta = 0.01
theta = gradient_descent(X_b,y,initial_theta,eta)

Wall time: 3.08 s


In [23]:
initial_theta

array([0., 0.])

In [ ]:
X_b = np.hstack([np.ones((len(X),1)),X])
initial_theta = np.zeros(X_b.shape[1])  #初始的theta值全为0
eta =0.01  #设置学习率
%time theta = gradient_descent(dJ_debug,X_b,y,initial_theta,eta)
theta

In [24]:
theta

array([3.00332687, 4.0037544 ])

### 随机梯度下降法


In [38]:
def J(theta , X_b , y):
    try :
        return np.sum((y - X_b.dot(theta)) **2 )/len(y)
    except:
        return float('inf')
    
def dJ_sgd(theta,X_b_i,y_i):
    
    return X_b_i.T.dot(X_b_i.dot(theta)- y_i)*2.
    

In [39]:
def sgd(X_b,y,initial_theta,n_iters): 
    
    t0 = 5
    t1 = 50
    def learing_rate(t):  
        return t0/(t+t1)
        #随机梯度下降法
    theta = initial_theta
    for cur_iter in range(n_iters):
        rand_i = np.random.randint(len(X_b))
        gradient = dJ_sgd(theta,X_b[rand_i],y[rand_i])
        theta = theta - learing_rate(cur_iter) * gradient
    return theta
        

In [40]:
%%time 
X_b = np.hstack([np.ones((len(X),1)),X])
initial_theta = np.zeros(X_b.shape[1])
theta = sgd(X_b , y , initial_theta , n_iters= len(X_b)//3)

Wall time: 928 ms


In [41]:
theta

array([3.00079228, 3.98521851])

In [42]:
len(X_b)

100000

In [1]:
from pycharm_project.LinearRegression import LinearRegression

In [2]:
lin_reg = LinearRegression()

In [3]:
lin_reg.fit_dg(X,y)

NameError: name 'X' is not defined