In [1]:
import numpy as np
import matplotlib.pyplot as plt
m = 100000

x = np.random.random(size = m)
X = x.reshape(-1,1)
y = x * 4. + 3. + np.random.normal(0,3,size = m)

In [2]:
y

array([ 9.12462312,  6.48597106,  2.81888075, ..., -0.1418627 ,
        1.93859322,  3.41421408])

In [3]:
X

array([[0.67612294],
       [0.24565846],
       [0.60677209],
       ...,
       [0.73664519],
       [0.42514548],
       [0.2668309 ]])

In [4]:
from pycharm_project.LinearRegression import LinearRegression

In [5]:
lin_reg = LinearRegression()

In [6]:
lin_reg.fit_sgd(X,y,n_iters =2)

In [7]:
lin_reg.coef_

array([4.33105398])

In [8]:
lin_reg.interception_

2.8916292466720797

In [9]:
lin_reg.fit_sgd(X,y,n_iters =2)

### 真实的使用我们的SGD

In [10]:
from sklearn import datasets

In [11]:
boston  = datasets.load_boston()

In [12]:
X = boston.data
y = boston.target

X = X[y<50.0]
y = y[y<50.0]


In [13]:
from sklearn.model_selection import train_test_split
X_train , X_test , y_train, y_test = train_test_split(X,y)

In [14]:
from sklearn.preprocessing import StandardScaler #对数据进行归一化处理
standardScaler = StandardScaler()
standardScaler.fit(X_train)
X_train_standard = standardScaler.transform(X_train)
X_test_standard = standardScaler.transform(X_test)

In [15]:
from pycharm_project.LinearRegression import LinearRegression

In [16]:
lin_reg2 = LinearRegression()

In [17]:
lin_reg2.fit_sgd(X_train_standard,y_train,n_iters=50)


In [19]:
lin_reg2.score(X_test_standard,y_test)

-3.599759723013388e+38

In [20]:
lin_reg2.coef_

array([ 2.07039068e+19, -3.53664194e+19, -6.96292995e+19,  1.56313384e+19,
       -1.03001283e+19,  3.38663800e+19, -8.74236316e+18, -7.74575513e+18,
       -3.27372168e+20,  3.55885303e+20,  7.51952586e+18, -1.18381350e+18,
        1.68611808e+19])

### sklearn 中的SGD

In [21]:
from sklearn.linear_model import SGDRegressor

In [27]:
sgd_reg = SGDRegressor(n_iter=100)
%time sgd_reg.fit(X_train_standard,y_train)
sgd_reg.score(X_test_standard,y_test)

Wall time: 8 ms


E:\Anaconda3\lib\site-packages\sklearn\linear_model\stochastic_gradient.py:117: DeprecationWarning: n_iter parameter is deprecated in 0.19 and will be removed in 0.21. Use max_iter and tol instead.
  DeprecationWarning)


0.7010723568641579